version: '3.1'

services:
  php_7: #first container
    build:
        context: .
        dockerfile: Dockerfile
    ports:
      - "85:80" #browse localhost:85 on browser
    volumes:
      - ./src:/var/www/html/ #set up source file volume inside src folder
  php_8: #second container
    build:
      context: .
      dockerfile: Dockerfile-php8
    ports:
      - "90:80" #browse localhost:90 on browser
    volumes:
      - ./php8:/var/www/html/ #set up source file volume inside php8 folder
  db: #third container
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

#setup a volume on your local system, all DB tables gets stored inside "mysqldata".
volumes:
  mysql-data: